# Generated by Django 4.2.5 on 2023-09-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("amount", models.IntegerField()),
                ("description", models.TextField()),
                ("card_type", models.CharField(max_length=200)),
                ("passcode", models.IntegerField()),
                ("attribute", models.CharField(max_length=200, null=True)),
                ("types", models.CharField(max_length=200, null=True)),
                ("level", models.IntegerField(null=True)),
                ("atk", models.IntegerField(null=True)),
                ("deff", models.IntegerField(null=True)),
                ("effect_type", models.CharField(max_length=200, null=True)),
                ("card_property", models.CharField(max_length=200, null=True)),
                ("rulings", models.TextField(null=True)),
                ("image_url", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
