# Generated by Django 4.2.5 on 2023-09-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="image_url",
        ),
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
